<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
  /**
   * Run the migrations.
   */
  public function up(): void
  {
    DB::table('sys_permisos')->insert([
      // Configuración sistema
      [
        'permiso_id'    => 1,
        'codigo'        => 'artegrafico.configuracion.sistema.usuarios.agregar',
        'titulo'        => 'Alta de usuario.',
        'descripcion'   => 'Permite dar de alta usuarios.',
        'seccion'       => 'Configuración Sistema',
        'orden_seccion' => 1,
      ],
      [
        'permiso_id'    => 2,
        'codigo'        => 'artegrafico.configuracion.sistema.usuarios.editar',
        'titulo'        => 'Edición de usuario.',
        'descripcion'   => 'Permite editar usuarios.',
        'seccion'       => 'Configuración Sistema',
        'orden_seccion' => 1,
      ],
      [
        'permiso_id'    => 3,
        'codigo'        => 'artegrafico.configuracion.sistema.usuarios.eliminar',
        'titulo'        => 'Eliminación de usuario.',
        'descripcion'   => 'Permite eliminar usuarios.',
        'seccion'       => 'Configuración Sistema',
        'orden_seccion' => 1,
      ],
      [
        'permiso_id'    => 4,
        'codigo'        => 'artegrafico.configuracion.sistema.usuarios.cambiarContrasena',
        'titulo'        => 'Edición contraseña de usuario.',
        'descripcion'   => 'Permite eliminar usuarios.',
        'seccion'       => 'Configuración Sistema',
        'orden_seccion' => 1,
      ],
      [
        'permiso_id'    => 5,
        'codigo'        => 'artegrafico.configuracion.sistema.usuarios.editarRelacionSucursales',
        'titulo'        => 'Edición relación con sucursales.',
        'descripcion'   => 'Permite editar la relación de un usuario con las sucursales.',
        'seccion'       => 'Configuración Sistema',
        'orden_seccion' => 1,
      ],
      [
        'permiso_id'    => 6,
        'codigo'        => 'artegrafico.configuracion.sistema.perfiles.agregar',
        'titulo'        => 'Alta de perfiles.',
        'descripcion'   => 'Permite dar de alta perfiles de acceso.',
        'seccion'       => 'Configuración Sistema',
        'orden_seccion' => 1,
      ],
      [
        'permiso_id'    => 7,
        'codigo'        => 'artegrafico.configuracion.sistema.perfiles.editar',
        'titulo'        => 'Edición de perfiles.',
        'descripcion'   => 'Permite editar perfiles de acceso.',
        'seccion'       => 'Configuración Sistema',
        'orden_seccion' => 1,
      ],
      [
        'permiso_id'    => 8,
        'codigo'        => 'artegrafico.configuracion.sistema.perfiles.eliminar',
        'titulo'        => 'Eliminación de perfiles.',
        'descripcion'   => 'Permite eliminar perfiles de acceso.',
        'seccion'       => 'Configuración Sistema',
        'orden_seccion' => 1,
      ],
      [
        'permiso_id'    => 9,
        'codigo'        => 'artegrafico.configuracion.sistema.perfiles.editarPermisos',
        'titulo'        => 'Edición permisos de perfil.',
        'descripcion'   => 'Permite editar los permisos relacionados al perfil.',
        'seccion'       => 'Configuración Sistema',
        'orden_seccion' => 1,
      ],
      [
        'permiso_id'    => 10,
        'codigo'        => 'artegrafico.configuracion.sistema.sucursales.agregar',
        'titulo'        => 'Alta de sucursales.',
        'descripcion'   => 'Permite dar de alta sucursales.',
        'seccion'       => 'Configuración Sistema',
        'orden_seccion' => 1,
      ],
      [
        'permiso_id'    => 11,
        'codigo'        => 'artegrafico.configuracion.sistema.sucursales.editar',
        'titulo'        => 'Edición de sucursales.',
        'descripcion'   => 'Permite editar sucursales.',
        'seccion'       => 'Configuración Sistema',
        'orden_seccion' => 1,
      ],
      [
        'permiso_id'    => 12,
        'codigo'        => 'artegrafico.configuracion.sistema.sucursales.eliminar',
        'titulo'        => 'Eliminación de sucursales.',
        'descripcion'   => 'Permite eliminar sucursales.',
        'seccion'       => 'Configuración Sistema',
        'orden_seccion' => 1,
      ],
      // Configuración contratos
      [
        'permiso_id'    => 13,
        'codigo'        => 'artegrafico.configuracion.contratos.universidades.agregar',
        'titulo'        => 'Alta de universidades.',
        'descripcion'   => 'Permite dar de alta universidades.',
        'seccion'       => 'Contratos configuración',
        'orden_seccion' => 2,
      ],
      [
        'permiso_id'    => 14,
        'codigo'        => 'artegrafico.configuracion.contratos.universidades.editar',
        'titulo'        => 'Edición de universidades.',
        'descripcion'   => 'Permite editar universidades.',
        'seccion'       => 'Contratos configuración',
        'orden_seccion' => 2,
      ],
      [
        'permiso_id'    => 15,
        'codigo'        => 'artegrafico.configuracion.contratos.universidades.eliminar',
        'titulo'        => 'Eliminación de universidades.',
        'descripcion'   => 'Permite eliminar universidades.',
        'seccion'       => 'Contratos configuración',
        'orden_seccion' => 2,
      ],
      [
        'permiso_id'    => 16,
        'codigo'        => 'artegrafico.configuracion.contratos.escuelas.agregar',
        'titulo'        => 'Alta de escuelas.',
        'descripcion'   => 'Permite dar de alta escuelas.',
        'seccion'       => 'Contratos configuración',
        'orden_seccion' => 2,
      ],
      [
        'permiso_id'    => 17,
        'codigo'        => 'artegrafico.configuracion.contratos.escuelas.editar',
        'titulo'        => 'Edición de escuelas.',
        'descripcion'   => 'Permite editar escuelas.',
        'seccion'       => 'Contratos configuración',
        'orden_seccion' => 2,
      ],
      [
        'permiso_id'    => 18,
        'codigo'        => 'artegrafico.configuracion.contratos.escuelas.eliminar',
        'titulo'        => 'Eliminación de escuelas.',
        'descripcion'   => 'Permite eliminar escuelas.',
        'seccion'       => 'Contratos configuración',
        'orden_seccion' => 2,
      ],
      [
        'permiso_id'    => 19,
        'codigo'        => 'artegrafico.configuracion.contratos.carreras.agregar',
        'titulo'        => 'Alta de carreras.',
        'descripcion'   => 'Permite dar de alta carreras.',
        'seccion'       => 'Contratos configuración',
        'orden_seccion' => 2,
      ],
      [
        'permiso_id'    => 20,
        'codigo'        => 'artegrafico.configuracion.contratos.carreras.editar',
        'titulo'        => 'Edición de carreras.',
        'descripcion'   => 'Permite editar carreras.',
        'seccion'       => 'Contratos configuración',
        'orden_seccion' => 2,
      ],
      [
        'permiso_id'    => 21,
        'codigo'        => 'artegrafico.configuracion.contratos.carreras.eliminar',
        'titulo'        => 'Eliminación de carreras.',
        'descripcion'   => 'Permite eliminar carreras.',
        'seccion'       => 'Contratos configuración',
        'orden_seccion' => 2,
      ],
      [
        'permiso_id'    => 22,
        'codigo'        => 'artegrafico.configuracion.contratos.grupos.agregar',
        'titulo'        => 'Alta de grupos.',
        'descripcion'   => 'Permite dar de alta grupos.',
        'seccion'       => 'Contratos configuración',
        'orden_seccion' => 2,
      ],
      [
        'permiso_id'    => 23,
        'codigo'        => 'artegrafico.configuracion.contratos.grupos.editar',
        'titulo'        => 'Edición de grupos.',
        'descripcion'   => 'Permite editar grupos.',
        'seccion'       => 'Contratos configuración',
        'orden_seccion' => 2,
      ],
      [
        'permiso_id'    => 24,
        'codigo'        => 'artegrafico.configuracion.contratos.grupos.eliminar',
        'titulo'        => 'Eliminación de grupos.',
        'descripcion'   => 'Permite eliminar grupos.',
        'seccion'       => 'Contratos configuración',
        'orden_seccion' => 2,
      ],
      // Contratos grupales
      [
        'permiso_id'    => 25,
        'codigo'        => 'artegrafico.contratos.grupales.agregar',
        'titulo'        => 'Alta de contratos grupales.',
        'descripcion'   => 'Permite dar de alta contratos grupales.',
        'seccion'       => 'Contratos grupales',
        'orden_seccion' => 3,
      ],
      [
        'permiso_id'    => 26,
        'codigo'        => 'artegrafico.contratos.grupales.editarFechas',
        'titulo'        => 'Edición de fechas.',
        'descripcion'   => 'Permite editar fechas en contratos grupales.',
        'seccion'       => 'Contratos grupales',
        'orden_seccion' => 3,
      ],
      // Contratos individuales
      [
        'permiso_id'    => 27,
        'codigo'        => 'artegrafico.contratos.individuales.agregar',
        'titulo'        => 'Alta de contratos individuales.',
        'descripcion'   => 'Permite dar de alta contratos individuales.',
        'seccion'       => 'Contratos individuales',
        'orden_seccion' => 4,
      ],
      [
        'permiso_id'    => 28,
        'codigo'        => 'artegrafico.contratos.individuales.editar',
        'titulo'        => 'Edición de contratos individuales.',
        'descripcion'   => 'Permite editar contratos individuales.',
        'seccion'       => 'Contratos individuales',
        'orden_seccion' => 4,
      ],
      [
        'permiso_id'    => 29,
        'codigo'        => 'artegrafico.contratos.individuales.eliminar',
        'titulo'        => 'Eliminación de contratos individuales.',
        'descripcion'   => 'Permite eliminar contratos individuales.',
        'seccion'       => 'Contratos individuales',
        'orden_seccion' => 4,
      ],
      // Artículos
      [
        'permiso_id'    => 30,
        'codigo'        => 'artegrafico.articulos.lineas.agregar',
        'titulo'        => 'Alta de lineas.',
        'descripcion'   => 'Permite dar de alta lineas.',
        'seccion'       => 'Articulos',
        'orden_seccion' => 5,
      ],
      [
        'permiso_id'    => 31,
        'codigo'        => 'artegrafico.articulos.lineas.editar',
        'titulo'        => 'Edición de lineas.',
        'descripcion'   => 'Permite editar lineas.',
        'seccion'       => 'Articulos',
        'orden_seccion' => 5,
      ],
      [
        'permiso_id'    => 32,
        'codigo'        => 'artegrafico.articulos.lineas.eliminar',
        'titulo'        => 'Eliminación de lineas.',
        'descripcion'   => 'Permite eliminar lineas.',
        'seccion'       => 'Articulos',
        'orden_seccion' => 5,
      ],
      [
        'permiso_id'    => 33,
        'codigo'        => 'artegrafico.articulos.modelos.agregar',
        'titulo'        => 'Alta de modelos.',
        'descripcion'   => 'Permite dar de alta modelos.',
        'seccion'       => 'Articulos',
        'orden_seccion' => 5,
      ],
      [
        'permiso_id'    => 34,
        'codigo'        => 'artegrafico.articulos.modelos.editar',
        'titulo'        => 'Edición de modelos.',
        'descripcion'   => 'Permite editar modelos.',
        'seccion'       => 'Articulos',
        'orden_seccion' => 5,
      ],
      [
        'permiso_id'    => 35,
        'codigo'        => 'artegrafico.articulos.modelos.eliminar',
        'titulo'        => 'Eliminación de modelos.',
        'descripcion'   => 'Permite eliminar modelos.',
        'seccion'       => 'Articulos',
        'orden_seccion' => 5,
      ],
      [
        'permiso_id'    => 36,
        'codigo'        => 'artegrafico.articulos.paquete.agregar',
        'titulo'        => 'Alta de artículos de paquete.',
        'descripcion'   => 'Permite dar de alta artículos de paquete.',
        'seccion'       => 'Articulos',
        'orden_seccion' => 5,
      ],
      [
        'permiso_id'    => 37,
        'codigo'        => 'artegrafico.articulos.paquete.editar',
        'titulo'        => 'Edición de artículos de paquete.',
        'descripcion'   => 'Permite editar artículos de paquete.',
        'seccion'       => 'Articulos',
        'orden_seccion' => 5,
      ],
      [
        'permiso_id'    => 38,
        'codigo'        => 'artegrafico.articulos.paquete.eliminar',
        'titulo'        => 'Eliminación de artículos de paquete.',
        'descripcion'   => 'Permite eliminar artículos de paquete.',
        'seccion'       => 'Articulos',
        'orden_seccion' => 5,
      ],
      [
        'permiso_id'    => 39,
        'codigo'        => 'artegrafico.articulos.parametros.agregar',
        'titulo'        => 'Alta de parametros.',
        'descripcion'   => 'Permite dar de alta parametros.',
        'seccion'       => 'Articulos',
        'orden_seccion' => 5,
      ],
      [
        'permiso_id'    => 40,
        'codigo'        => 'artegrafico.articulos.parametros.editar',
        'titulo'        => 'Edición de parametros.',
        'descripcion'   => 'Permite editar parametros.',
        'seccion'       => 'Articulos',
        'orden_seccion' => 5,
      ],
      [
        'permiso_id'    => 41,
        'codigo'        => 'artegrafico.articulos.parametros.eliminar',
        'titulo'        => 'Eliminación de parametros.',
        'descripcion'   => 'Permite eliminar parametros.',
        'seccion'       => 'Articulos',
        'orden_seccion' => 5,
      ],
      [
        'permiso_id'    => 42,
        'codigo'        => 'artegrafico.articulos.agregar',
        'titulo'        => 'Alta de artículos.',
        'descripcion'   => 'Permite dar de alta artículos.',
        'seccion'       => 'Articulos',
        'orden_seccion' => 5,
      ],
      [
        'permiso_id'    => 43,
        'codigo'        => 'artegrafico.articulos.editar',
        'titulo'        => 'Edición de artículos.',
        'descripcion'   => 'Permite editar artículos.',
        'seccion'       => 'Articulos',
        'orden_seccion' => 5,
      ],
      [
        'permiso_id'    => 44,
        'codigo'        => 'artegrafico.articulos.eliminar',
        'titulo'        => 'Eliminación de artículos.',
        'descripcion'   => 'Permite eliminar artículos.',
        'seccion'       => 'Articulos',
        'orden_seccion' => 5,
      ],
      [
        'permiso_id'    => 45,
        'codigo'        => 'artegrafico.articulos.editar.imagen',
        'titulo'        => 'Editar imagen base de articulo.',
        'descripcion'   => 'Permite editar la imagen base de los artículos.',
        'seccion'       => 'Articulos',
        'orden_seccion' => 5,
      ],
      [
        'permiso_id'    => 46,
        'codigo'        => 'artegrafico.configuracion.sistema.usuarios.editar.imagen',
        'titulo'        => 'Editar imagen de usuario.',
        'descripcion'   => 'Permite editar la imagen de los usuarios.',
        'seccion'       => 'Configuración Sistema',
        'orden_seccion' => 1,
      ],
      [
        'permiso_id'    => 47,
        'codigo'        => 'artegrafico.articulos.plantillas.editar',
        'titulo'        => 'Edición de plantillas.',
        'descripcion'   => 'Permite editar plantillas.',
        'seccion'       => 'Articulos',
        'orden_seccion' => 5,
      ],
      [
        'permiso_id'    => 48,
        'codigo'        => 'artegrafico.articulos.combinaciones.agregar',
        'titulo'        => 'Alta de combinaciones.',
        'descripcion'   => 'Permite dar de alta combinaciones.',
        'seccion'       => 'Articulos',
        'orden_seccion' => 5,
      ],
      [
        'permiso_id'    => 49,
        'codigo'        => 'artegrafico.articulos.combinaciones.editar',
        'titulo'        => 'Edición de combinaciones.',
        'descripcion'   => 'Permite editar combinaciones.',
        'seccion'       => 'Articulos',
        'orden_seccion' => 5,
      ],
      [
        'permiso_id'    => 50,
        'codigo'        => 'artegrafico.articulos.combinaciones.eliminar',
        'titulo'        => 'Eliminación de combinaciones.',
        'descripcion'   => 'Permite eliminar combinaciones.',
        'seccion'       => 'Articulos',
        'orden_seccion' => 5,
      ],
      [
        'permiso_id'    => 51,
        'codigo'        => 'artegrafico.paquetes.agregar',
        'titulo'        => 'Alta de paquetes.',
        'descripcion'   => 'Permite dar de alta paquetes.',
        'seccion'       => 'Paquetes',
        'orden_seccion' => 6,
      ],
      [
        'permiso_id'    => 52,
        'codigo'        => 'artegrafico.paquetes.editar',
        'titulo'        => 'Edición de paquetes.',
        'descripcion'   => 'Permite editar paquetes.',
        'seccion'       => 'Paquetes',
        'orden_seccion' => 6,
      ],
      [
        'permiso_id'    => 53,
        'codigo'        => 'artegrafico.paquetes.eliminar',
        'titulo'        => 'Eliminación de paquetes.',
        'descripcion'   => 'Permite eliminar paquetes.',
        'seccion'       => 'Paquetes',
        'orden_seccion' => 6,
      ],
      [
        'permiso_id'    => 54,
        'codigo'        => 'artegrafico.articulos.clonar',
        'titulo'        => 'Clonación de articulos.',
        'descripcion'   => 'Permite clonar articulos.',
        'seccion'       => 'Articulos',
        'orden_seccion' => 5,
      ],
      [
        'permiso_id'    => 55,
        'codigo'        => 'artegrafico.contratos.grupales.agregar.paquete',
        'titulo'        => 'Agregar paquetes a contratos grupales.',
        'descripcion'   => 'Permite agregar paquetes a contratos grupales.',
        'seccion'       => 'Contratos grupales',
        'orden_seccion' => 3,
      ],
      [
        'permiso_id'    => 56,
        'codigo'        => 'artegrafico.articulos.combinaciones.editar.imagen',
        'titulo'        => 'Editar imagen de combinaciones.',
        'descripcion'   => 'Permite editar la imagen de las combinaciones.',
        'seccion'       => 'Articulos',
        'orden_seccion' => 5,
      ],
      [
        'permiso_id'    => 57,
        'codigo'        => 'artegrafico.paquetes.editar.imagen',
        'titulo'        => 'Editar imagen de paquetes.',
        'descripcion'   => 'Permite editar la imagen de los paquetes.',
        'seccion'       => 'Paquetes',
        'orden_seccion' => 6,
      ],
      [
        'permiso_id'    => 58,
        'codigo'        => 'artegrafico.paquetes.eliminar.linea',
        'titulo'        => 'Eliminar linea del paquete.',
        'descripcion'   => 'Permite eliminar relación de linea con un paquete.',
        'seccion'       => 'Paquetes',
        'orden_seccion' => 6,
      ],
      [
        'permiso_id'    => 59,
        'codigo'        => 'artegrafico.contratos.grupales.eliminar.paquete',
        'titulo'        => 'Eliminar paquetes de contratos grupales.',
        'descripcion'   => 'Permite eliminar paquetes de contratos grupales.',
        'seccion'       => 'Contratos grupales',
        'orden_seccion' => 3,
      ],
      [
        'permiso_id'    => 60,
        'codigo'        => 'artegrafico.articulos.modelos.editar.imagen',
        'titulo'        => 'Editar imagen de modelos.',
        'descripcion'   => 'Permite editar la imagen de los modelos.',
        'seccion'       => 'Articulos',
        'orden_seccion' => 5,
      ],
      [
        'permiso_id'    => 61,
        'codigo'        => 'artegrafico.articulos.paquete.editar.imagen',
        'titulo'        => 'Editar imagen de articulos paquete.',
        'descripcion'   => 'Permite editar la imagen de los articulos paquete.',
        'seccion'       => 'Articulos',
        'orden_seccion' => 5,
      ],
      [
        'permiso_id'    => 62,
        'codigo'        => 'artegrafico.contratos.grupales.publicar',
        'titulo'        => 'Publicar contrato grupal.',
        'descripcion'   => 'Permite publicar un contrato grupal.',
        'seccion'       => 'Contratos grupales',
        'orden_seccion' => 3,
      ],
      [
        'permiso_id'    => 63,
        'codigo'        => 'artegrafico.contratos.grupales.editar',
        'titulo'        => 'Editar contrato grupal.',
        'descripcion'   => 'Permite editar un contrato grupal.',
        'seccion'       => 'Contratos grupales',
        'orden_seccion' => 3,
      ],
      [
        'permiso_id'    => 64,
        'codigo'        => 'artegrafico.contratos.grupales.eliminar',
        'titulo'        => 'Eliminar contrato grupal.',
        'descripcion'   => 'Permite eliminar un contrato grupal.',
        'seccion'       => 'Contratos grupales',
        'orden_seccion' => 3,
      ],
      [
        'permiso_id'    => 65,
        'codigo'        => 'artegrafico.articulos.dedicatorias.agregar',
        'titulo'        => 'Alta de dedicatorias.',
        'descripcion'   => 'Permite dar de alta dedicatorias.',
        'seccion'       => 'Articulos',
        'orden_seccion' => 5,
      ],
      [
        'permiso_id'    => 66,
        'codigo'        => 'artegrafico.articulos.dedicatorias.editar',
        'titulo'        => 'Edición de dedicatorias.',
        'descripcion'   => 'Permite editar dedicatorias.',
        'seccion'       => 'Articulos',
        'orden_seccion' => 5,
      ],
      [
        'permiso_id'    => 67,
        'codigo'        => 'artegrafico.articulos.dedicatorias.eliminar',
        'titulo'        => 'Eliminación de dedicatorias.',
        'descripcion'   => 'Permite eliminar dedicatorias.',
        'seccion'       => 'Articulos',
        'orden_seccion' => 5,
      ],
    ]);
  }

  /**
   * Reverse the migrations.
   */
  public function down(): void
  {
    DB::table('sys_permisos')->whereIn('codigo', [
      'artegrafico.configuracion.sistema.usuarios.agregar',
      'artegrafico.configuracion.sistema.usuarios.editar',
      'artegrafico.configuracion.sistema.usuarios.eliminar',
      'artegrafico.configuracion.sistema.usuarios.cambiarContrasena',
      'artegrafico.configuracion.sistema.perfiles.agregar',
      'artegrafico.configuracion.sistema.perfiles.editar',
      'artegrafico.configuracion.sistema.perfiles.eliminar',
      'artegrafico.configuracion.sistema.perfiles.editarPermisos',
      'artegrafico.configuracion.sistema.sucursales.agregar',
      'artegrafico.configuracion.sistema.sucursales.editar',
      'artegrafico.configuracion.sistema.sucursales.eliminar',
      'artegrafico.configuracion.contratos.universidades.agregar',
      'artegrafico.configuracion.contratos.universidades.editar',
      'artegrafico.configuracion.contratos.universidades.eliminar',
      'artegrafico.configuracion.contratos.escuelas.agregar',
      'artegrafico.configuracion.contratos.escuelas.editar',
      'artegrafico.configuracion.contratos.escuelas.eliminar',
      'artegrafico.configuracion.contratos.carreras.agregar',
      'artegrafico.configuracion.contratos.carreras.editar',
      'artegrafico.configuracion.contratos.carreras.eliminar',
      'artegrafico.configuracion.contratos.grupos.agregar',
      'artegrafico.configuracion.contratos.grupos.editar',
      'artegrafico.configuracion.contratos.grupos.eliminar',
      'artegrafico.contratos.grupales.agregar',
      'artegrafico.contratos.grupales.editarFechas',
      'artegrafico.contratos.individuales.agregar',
      'artegrafico.contratos.individuales.editar',
      'artegrafico.contratos.individuales.eliminar',
      'artegrafico.articulos.editar.imagen',
      'artegrafico.configuracion.sistema.usuarios.editar.imagen',
      'artegrafico.articulos.plantillas.editar',
      'artegrafico.articulos.combinaciones.agregar',
      'artegrafico.articulos.combinaciones.editar',
      'artegrafico.articulos.combinaciones.eliminar',
      'artegrafico.paquetes.agregar',
      'artegrafico.paquetes.editar',
      'artegrafico.paquetes.eliminar',
      'artegrafico.articulos.clonar',
      'artegrafico.contratos.grupales.agregar.paquete',
      'artegrafico.articulos.combinaciones.editar.imagen',
      'artegrafico.paquetes.editar.imagen',
      'artegrafico.paquetes.eliminar.linea',
      'artegrafico.contratos.grupales.eliminar.paquete',
      'artegrafico.articulos.modelos.editar.imagen',
      'artegrafico.articulos.paquete.editar.imagen',
      'artegrafico.contratos.grupales.publicar',
      'artegrafico.contratos.grupales.editar',
      'artegrafico.contratos.grupales.eliminar',
      'artegrafico.articulos.dedicatorias.agregar',
      'artegrafico.articulos.dedicatorias.editar',
      'artegrafico.articulos.dedicatorias.eliminar',
    ])->delete();
  }
};
